# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 725b1a7b76886d4c902e97a05db4510044591c6bd5085192ce6703515e2e2ed1c0dc8ba0b7dbd01e8b745cfb36b712b3b622ade7cfc2e84337d3ba365d7dfb47

test:
  secret_key_base: 7bc5ba1b3eaf5e2552a193f6d49d3dab28990accf877ff1455308e0da7a1ca1a6dfd757ace6edb9b8ea7b8991671c2a4a904d4e5b43144c8327e297d62aec549

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
